---
image: python:2.7-alpine

stages:
  - staticcheck
  - unittest

variables:
    DOCKER_FIX: ""

staticcheck:
  stage: staticcheck
  before_script:
    - pip install -U flake8
  script:
    - flake8 --max-line-length=248 project/

unittest:
  stage: unittest
  script:
     - echo 'Skip unittest until it is ready'
